cleanup some code
gaeulbyul/MirrorBlock pull request #3
Opened 2018-01-27 21:01 UTC by OnLiU211

2018-01-29 07:07 UTC, gaeulbyul requested changes

2018-01-29 07:07 UTC, gaeulbyul commented on MirrorOfBlock/scripts/chainblock.js
> +          if (!shouldContinue) {
이 부분을 바꾸신 이유가 있나요? `if`에 부정조건문을 넣으면 `else`문은 이중부정의 형태가 되버리는데요...

2018-01-29 07:07 UTC, gaeulbyul commented on MirrorOfBlock/scripts/chainblock.js
> +        (reason === 'muted') ? '[Skip]' : ''
굳이 삼항연산자로 줄일 필요는 없을 것 같습니다... 만약 `userPrefix`를 `const`변수로 만들려는 의도였다면
```javascript
const userPrefixes = {
  'already-blocked': '[Blocked] ',
  'muted': '[Skip] '
}
const userPrefix = userPrefixes[reason]
```
...위와 같은 형태가 더 낫지 않을까 싶습니다.

2018-03-27 22:21 UTC, closed without merging

2018-04-05 14:03 UTC, OnLiU211 commented on MirrorOfBlock/scripts/chainblock.js
> +          if (!shouldContinue) {
가독성 차원에서 이편이 더 파악하기 쉽다고 생각해요